-- View: vw_product_performance
-- Purpose: Analyze product sales metrics, total revenue, average unit price, and order volume
-- Business Question: Which products and product categories drive the highest sales volume and gross revenue?
-- Updated: Automatically recalculated on demand upon every query invocation
-- Used by: Executive sales dashboard, inventory planning, product performance analytics
--
-- Columns:
--   product_id: Unique identifier for product
--   product_name: Display name of product
--   category: Product category classification (e.g. Cloud, Database, Security)
--   total_orders: Count of distinct orders containing this product
--   units_sold: Total cumulative units sold across all orders
--   total_revenue: Total gross revenue generated by sales of this product
--   avg_unit_price: Average price per unit across sales items
--   last_sold_date: Date of most recent order for this product

CREATE VIEW IF NOT EXISTS vw_product_performance AS
SELECT 
    p.product_id,
    p.product_name,
    p.category,
    COUNT(DISTINCT oi.order_id) AS total_orders,
    COALESCE(SUM(oi.quantity), 0) AS units_sold,
    COALESCE(SUM(oi.quantity * oi.unit_price), 0) AS total_revenue,
    COALESCE(AVG(oi.unit_price), 0) AS avg_unit_price,
    MAX(o.order_date) AS last_sold_date
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE oi.quantity > 0
GROUP BY p.product_id, p.product_name, p.category;
